name: Test
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.8", "3.10" ]
    steps:
      - uses: actions/checkout@v1
      - name: Install poetry
        run: pip install poetry
      - name: Install dependencies
        run: poetry install
      - name: Test
        run: pytest -svv --cov=bento_drop_box_service --cov-branch
      - name: Codecov
        run: codecov
